In [17]:
import torch
beams = 4
b_tag = torch.ones((5)) * beams
print(b_tag)
b = torch.tensor([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
x = torch.tensor([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
y = torch.tensor([[0.1, 0.4, 0.7, 0.8], [0.1, 0.9, 0.6, 0.3], [1, 0.1, 0.6, 0.5], [1, 0.1, 0.2, 0.1]])
z = torch.stack((b,x,y), dim=-1)

# print(z)
# print(torch.flatten(z, start_dim=0, end_dim=1))
print(z.size())

flat_z = torch.flatten(z, start_dim=0, end_dim=1)

print(flat_z)

beam, idx, prob = flat_z[4]

print(beam)

top_k, top_k_idx = torch.topk(flat_z[:,-1], 4)

#top_k, top_k_idx = torch.topk(z[:,:,-1], 4)


print(top_k_idx)

tensor([4., 4., 4., 4., 4.])
torch.Size([4, 4, 3])
tensor([[1.0000, 1.0000, 0.1000],
        [1.0000, 2.0000, 0.4000],
        [1.0000, 3.0000, 0.7000],
        [1.0000, 4.0000, 0.8000],
        [2.0000, 1.0000, 0.1000],
        [2.0000, 2.0000, 0.9000],
        [2.0000, 3.0000, 0.6000],
        [2.0000, 4.0000, 0.3000],
        [3.0000, 1.0000, 1.0000],
        [3.0000, 2.0000, 0.1000],
        [3.0000, 3.0000, 0.6000],
        [3.0000, 4.0000, 0.5000],
        [4.0000, 1.0000, 1.0000],
        [4.0000, 2.0000, 0.1000],
        [4.0000, 3.0000, 0.2000],
        [4.0000, 4.0000, 0.1000]])
tensor(2.)
tensor([12,  8,  5,  3])
